meta_product_name: "Chez Maurice Production"
meta_title: "Chez Maurice Production | créateurs de contenu audiovisuels"
meta_description: "Nous sommes créateurs de contenus audiovisuels : film corporate, brand content, vidéo produit...
Nous abordons avec passion et créativité tous vos projets, des plus conventionnels aux plus décalés.
Réactifs et agiles, nous intervenons à chaque étape de la conception de votre film : conseil, scénarisation, tournage, et postproduction.
Chez Maurice, vous trouverez une équipe aux petits soins et l’expertise technique pour donner vie à tous vos projets !"
meta_image: "OGCARD.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
